//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonXuat
    {
        public HoaDonXuat()
        {
            this.ChiTietHDXes = new HashSet<ChiTietHDX>();
        }
    
        public long ID { get; set; }
        public long IDTK { get; set; }
        public string MaHDX { get; set; }
        public System.DateTime NgayXuat { get; set; }
        public double TongTien { get; set; }
        public string TenKhachHang { get; set; }
        public string DienThoai { get; set; }
    
        public virtual ICollection<ChiTietHDX> ChiTietHDXes { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
