//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonNhap
    {
        public HoaDonNhap()
        {
            this.ChiTietHDNs = new HashSet<ChiTietHDN>();
        }
    
        public long ID { get; set; }
        public long IDTaiKhoan { get; set; }
        public string MaHDN { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public double TongTien { get; set; }
    
        public virtual ICollection<ChiTietHDN> ChiTietHDNs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
