//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.ChiTietHDNs = new HashSet<ChiTietHDN>();
            this.ChiTietHDXes = new HashSet<ChiTietHDX>();
            this.DatHangs = new HashSet<DatHang>();
        }
    
        public long ID { get; set; }
        public long IDLoaiSP { get; set; }
        public long IDNCC { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public double SoLuong { get; set; }
        public string DonViTinh { get; set; }
        public double GiaNhap { get; set; }
        public double GiaBan { get; set; }
    
        public virtual ICollection<ChiTietHDN> ChiTietHDNs { get; set; }
        public virtual ICollection<ChiTietHDX> ChiTietHDXes { get; set; }
        public virtual ICollection<DatHang> DatHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
