//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.HoaDonNhaps = new HashSet<HoaDonNhap>();
            this.HoaDonXuats = new HashSet<HoaDonXuat>();
        }
    
        public long ID { get; set; }
        public string TaiKhoan1 { get; set; }
        public string MatKhau { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string AdminYN { get; set; }
    
        public virtual ICollection<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual ICollection<HoaDonXuat> HoaDonXuats { get; set; }
    }
}
