//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTongHopHDX
    {
        public double SoLuong { get; set; }
        public long ID { get; set; }
        public string MaHDX { get; set; }
        public System.DateTime NgayXuat { get; set; }
        public string TenSP { get; set; }
        public string DonViTinh { get; set; }
        public double TongTien { get; set; }
        public string TaiKhoan { get; set; }
        public double DonGia { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    }
}
