//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTongHopHDN
    {
        public double SoLuong { get; set; }
        public double Dongia { get; set; }
        public double VAT { get; set; }
        public string MaHDN { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public string TenNCC { get; set; }
        public string TenSP { get; set; }
        public string TaiKhoan { get; set; }
        public double TongTien { get; set; }
        public double ThanhTien { get; set; }
    }
}
