//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDatHang
    {
        public double SoLuong { get; set; }
        public string MaDatHang { get; set; }
        public long ID { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayNhan { get; set; }
        public string TenKhachHang { get; set; }
        public string DienThoai { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string DonViTinh { get; set; }
    }
}
